import Head from 'next/head';
import { Roboto } from '@next/font/google';
import localFont from '@next/font/local';
import { getGlobalLayout } from '@/components';
// main font
const roboto = Roboto({
  weight: ['100', '300', '400', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
});
// font for header
const fontKelSi = localFont({
  src: '../assets/font/kelsi/Kelsi-Regular.otf',
  variable: '--font-kelsi',
});
// className={``}
export function Home() {
  return (
    <main
      className={`flex min-h-screen flex-col items-center justify-between p-24 ${roboto.variable} ${fontKelSi.variable} font-sans`}
    >
      <Head>
        <title>Minsk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-center align-middle">
        <span className="font-fontHeader">Content</span>
      </div>
    </main>
  );
}

Home.getLayout = getGlobalLayout;

export default Home;
